"""empty message

Revision ID: b62f0b572db6
Revises: d70b7bf97b11
Create Date: 2023-10-22 15:23:26.828415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62f0b572db6'
down_revision = 'd70b7bf97b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods', schema=None) as batch_op:
        batch_op.alter_column('discount_price',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods', schema=None) as batch_op:
        batch_op.alter_column('discount_price',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
